service: serverless-tests

provider:
    name: aws
    stage: dev # Default stage
    region: eu-central-1 # Frankfurt

functions:
    readFunc: # function 1
        handler: read.func

# resources that functions use
resources:
    # this is Cloud Formation
    Resources:
        demoTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: my-table
                AttributeDefinitions:
                    # only one property. More columns will be added when items are added
                    - AttributeName: email
                      AttributeType: S # S(tring) or N(umber) or B(inary)
                KeySchema:
                    - AttributeName: email
                      KeyType: HASH # HASH or RANGE
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
