service: serverless-tests

provider:
    name: aws
    stage: dev # Default stage
    region: eu-central-1 # Frankfurt
    runtime: go1.x
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:DescribeStream
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:ListStreams
          Resource: arn:aws:dynamodb:*:*:table/my-table

functions:
    readFunc: # function 1
        handler: read.func
        events:
            - stream: arn:aws:dynamodb:eu-central-1:757691043963:table/my-table/stream/2018-05-10T16:34:23.265

# resources that functions use
resources:
    # this is Cloud Formation
    Resources:
        demoTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: my-table
                AttributeDefinitions:
                    # only one property. More columns will be added when items are added
                    - AttributeName: email
                      AttributeType: S # S(tring) or N(umber) or B(inary)
                KeySchema:
                    - AttributeName: email
                      KeyType: HASH # HASH or RANGE
                ProvisionedThroughput:
                    ReadCapacityUnits: 1 # number of columns ?
                    WriteCapacityUnits: 1
                # DynamoDB Stream enabled -> New and old images; triggers are defined in functions spec
                StreamSpecification:
                    StreamViewType: NEW_AND_OLD_IMAGES
